// <auto-generated />
using DHCardHelper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DHCardHelper.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DHCardHelper.Models.Entities.Cards.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("DomainId")
                        .HasColumnType("int");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("TypeId");

                    b.ToTable("Cards");

                    b.HasDiscriminator<string>("CardType").HasValue("Card");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DHCardHelper.Models.Entities.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("DHCardHelper.Models.Entities.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("DHCardHelper.Models.Entities.Cards.BackgroundCard", b =>
                {
                    b.HasBaseType("DHCardHelper.Models.Entities.Cards.Card");

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Background");
                });

            modelBuilder.Entity("DHCardHelper.Models.Entities.Cards.DomainCard", b =>
                {
                    b.HasBaseType("DHCardHelper.Models.Entities.Cards.Card");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("RecallCost")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Domain");
                });

            modelBuilder.Entity("DHCardHelper.Models.Entities.Cards.SubclassCard", b =>
                {
                    b.HasBaseType("DHCardHelper.Models.Entities.Cards.Card");

                    b.Property<string>("MasteryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Subclass");
                });

            modelBuilder.Entity("DHCardHelper.Models.Entities.Cards.Card", b =>
                {
                    b.HasOne("DHCardHelper.Models.Entities.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId");

                    b.HasOne("DHCardHelper.Models.Entities.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Domain");

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
